config/routes.rb
Qiqi::Application.routes.draw do
  root :to => "home#index"

  match "/login" => "sessions#new"
  match "/logout" => "sessions#destroy"
  match "/register" => "users#new"

  match "/session/create" => "sessions#create"

  match "/reply/new" => "replies#new"
  match "/reply/create" => "replies#create"
  match "/reply/:id" => "replies#reply", :as => :reply
  match "/reply/destroy/:id" => "replies#destroy", :as => :reply_destroy

  match "/topic/new" => "topics#new"
  match "/topic/create" => "topics#create"
  match "/topic/reply/:id" => "topics#reply", :as => :topic_reply
  match "/topic/destroy/:id" => "topics#destroy", :as => :topic_destroy

  match "/user/index" => "users#index"
  match "/user/create" => "users#create"
  match "/user/:username" => "users#single", :as => :user
  match "/user/destroy/:number" => "users#destroy", :as => :user_destroy
end

app/models/history.rb
class History
  include Mongoid::Document
end

app/models/reply.rb
class Reply
  include Mongoid::Document
  include Mongoid::Timestamps

  field :content

  validates_length_of :content, :minimum => 5

  belongs_to :user
  belongs_to :topic
  has_many :child_replies, :class_name => "Reply", :inverse_of => :parent_reply, :dependent => :destroy
  belongs_to :parent_reply, :class_name => "Reply", :inverse_of => :child_replies
end

app/models/topic.rb
class Topic
  include Mongoid::Document
  include Mongoid::Timestamps

  field :title
  field :content

  validates_length_of :title, :in => 2..50

  validates_length_of :content, :minimum => 20

  belongs_to :user
  has_many :replies, :dependent => :destroy
end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps

  attr_accessor :password
  attr_accessible :username, :email, :password, :password_confirmation

  field :username
  field :email

  field :password_hash
  field :password_salt

  field :points, :type => Integer, :default => 0

  auto_increment :number
  index :number, :unique => true

  validates_presence_of :password, :on => :create
  validates_length_of :password, :in => 8..20
  validates_confirmation_of :password

  validates_uniqueness_of :username
  validates_format_of :username, :with => %r/\A[a-z0-9][a-z0-9_-]{1,14}\Z/i

  validates_uniqueness_of :email
  validates_format_of :email, :with => %r/\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i

  has_many :topics, :dependent => :nullify
  has_many :replies, :dependent => :nullify

  before_save :encrypt_password

  def self.authenticate(username, password)
    user = where(:username => username).first
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

  class << self
    ["number", "username"].each do |s|
      define_method(:"find_by_#{s}") do |p|
        where(:"#{s}" => p).first
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_user, :logged_in?

  private

  def current_user
    @user ||= User.where(:number => session[:user_id]).first if session[:user_id]
  end

  def logged_in?
    !current_user.nil?
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if logged_in?
      redirect_to user_index_path(current_user.number)
    else
      redirect_to login_path
    end
  end
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
  before_filter :logged_in?

  def new
    @reply = Reply.new
  end

  def reply
    @user = User.find_by_number(current_user.number)
    @parent = Reply.find(params[:id])
    @child = @parent.child_replies.create(params[:reply])

    @child.user = @user

    if @user && @parent && @child.save
      respond_to do |format|
        format.js
      end
    else
      respond_to do |format|
        format.js { render "shared/fail_to_reply" }
      end
    end
  end

  def destroy
    @reply = Reply.find(params[:id])

    if @reply.try(:destroy)
      respond_to do |format|
        format.js
      end
    else
      respond_to do |format|
        format.js { render "shared/fail_to_destroy" }
      end
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  layout "index"

  def new
  end

  def create
    user = User.authenticate(params[:username], params[:password])

    if user
      session[:user_id] = user.number
      redirect_to user_index_url, :notice => "Logged in successfully!"
    else
      redirect_to login_url, :alert => "Invalid username or password, please try again!"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Logged out successfully!"
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_filter :logged_in?

  def index
    @topics = Topic.desc(:created_at).page.padding(2)
  end

  def new
    @topic = Topic.new
  end

  def create
    @user = User.find_by_number(current_user.number)
    @topic = @user.topics.create(params[:topic])

    if @topic.try(:save)
      respond_to do |format|
        format.js
      end
    else
      respond_to do |format|
        format.js { render "shared/fail_to_create" }
      end
    end
  end

  def reply
    @user = User.find_by_number(current_user.number)
    @topic = Topic.find(params[:id])
    @reply = @topic.replies.create(params[:reply])

    @reply.user = @user

    if @user && @topic && @reply.try(:save)
      respond_to do |format|
        format.js
      end
    else
      respond_to do |format|
        format.js { render "shared/fail_to_reply" }
      end
    end
  end

  def destroy
    @topic = Topic.find(params[:id])

    if @topic.try(:destroy)
      respond_to do |format|
        format.js
      end
    else
      respond_to do |format|
        format.js { render "shared/fail_to_destroy" }
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :logged_in?, :only => [:destroy]
  layout "index", :only => [:new]

  def index
    @user = current_user
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(params[:user])

    if @user.try(:save)
      redirect_to user_index_path
    else
      redirect_to register_path, :alert => "Unsuccessful. Please try again!"
    end
  end

  def single
    @user ||= User.find_by_username(params[:username])
  end

  def destroy
    @user ||= User.find_by_number(params[:number])

    if @user.try(:destroy)
      respond_to do |format|
        format.js
      end
    else
      respond_to do |format|
        format.js { render "shared/fail_to_destroy" }
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(content, options = {})
    markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, options)
    coderay(markdown.render(content)).html_safe
  end

  def coderay(content, options = {})
    defaults = {
      :line_number => :table,
    }

    content.gsub(/\*{3,}(.+?)\n(.+?)\*{3,}/m) do
      Coderay.scan($2, $1).div(defaults.merge(options))
    end
  end

  def at_notification(content, options = {})
    content.gsub(/(^|[^a-zA-Z0-9_!#\$%&*@])(@)([a-zA-Z0-9][a-zA-Z0-9_-]{1,14})/) do
      %(<a href="#{user_url($3)}" class="#{options[:class]}">#{$1 + $2 + $3}</a>)
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Qiqi</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Qiqi</title>
  <%= csrf_meta_tags %>

  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->

  <!-- Le styles -->
  <%= stylesheet_link_tag "application", :media => "all" %>

  <!-- Le fav and touch icons -->
  <link href="images/favicon.ico" rel="shortcut icon">
</head>
<body>

<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="brand" href="#">QiQi</a>

      <div class="container nav-collapse">
        <ul class="nav pull-right">
          <li><%= link_to "Index", root_path %></li>
          <li>
            <% if logged_in? %>
              <%= link_to "History", user_history_path(current_user.number) %>
            <% end %>
          </li>
          <li>
            <% if logged_in? %>
                <%= link_to "Logout", logout_path %>
            <% end %>
          </li>
        </ul>
      </div>
      <!--/.nav-collapse -->
    </div>
  </div>
</div>

<div class="container">
  <div class="content">
    <div class="auth margin-auto">
        <%= yield %>
    </div>
    <!--/row-->
  </div>
  <!--/content-->

  <hr />
  <footer>
    <p>&copy; <%= link_to "Tomato", "http://www.thesika.info" %> 2012</p>
  </footer>

</div>
<!-- /container -->

<!-- Le javascript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<%= javascript_include_tag "application" %>

</body>
</html>

app/views/topics/index.html.erb
<%= link_to "New Topic", topic_new_path, :remote => true %>

<% if @topics && @topics.any? %>
    <%= div_for @topics, :class => "topic" do |t| %>
        <%= t.title %>
    <% end %>
<% end %>

<%= paginate :topics, :remote => true %>

app/views/users/index.html.erb
<% if @user.topics %>
    <%= div_for @user.topics %>
<% end %>

<% if @user.replies %>
    <%= div_for @user.replies %>
<% end %>

app/views/users/new.html.erb
<%= form_for @user, :url => user_create_path do |f| %>
    <p><%= f.text_field :username, :placeholder => "Username", :class => "register-input" %></p>

    <p><%= f.password_field :password, :placeholder => "Password", :class => "register-input" %></p>

    <p><%= f.password_field :password_confirmation, :placeholder => "Confirm Password", :class => "register-input" %></p>

    <p><%= f.email_field :email, :placeholder => "Email", :class => "register-input" %></p>

    <%= f.submit :submit, :class => "register-btn" %>
<% end %>